### ISSUE TITLE
Link to CV not working 

### ISSUE THREAD

**Issue by verma-kunal** [Shanmuganathanb/Portfolio_1#1]
The link button to the CV doesn't seem to be configured properly as its not getting redirected the **CV**

## Button:
![Screenshot 2021-05-26 at 11 10 08 PM](https://user-images.githubusercontent.com/72245772/119706377-85328b80-be77-11eb-86d4-e27b503a0777.png)

## Page getting redirected here:
![Screenshot 2021-05-26 at 11 08 10 PM](https://user-images.githubusercontent.com/72245772/119706167-400e5980-be77-11eb-98bb-a6c29213f4b9.png)

**Comment by Shanmuganathanb** [comment]
Yeah ! Thanks for letting me know. Will fix it now. I think there is some mistake in path mentioning.

**Comment by Shanmuganathanb** [comment]
Yeah ! Thanks for letting me know. I will update it. I think there is some mistake in path mentioning . @verma-kunal

**Comment by Shanmuganathanb** [comment]
I fixed the issue and also updated my new CV too. Cheers !

**Comment by verma-kunal** [comment]
> I fixed the issue and also updated my new CV too. Cheers !

Thats awesome! 👍
