### ISSUE TITLE
Add porfolio link in about section

### ISSUE THREAD

**Issue by vikasganiga05** [Shanmuganathanb/Portfolio_1#2]
The portfolio website link is missing from the about section. Add [https://shanmuganathanb.github.io/Portfolio_1/](https://shanmuganathanb.github.io/Portfolio_1/) to the about section. Also add some description.

#### Screenshot

![image](https://user-images.githubusercontent.com/74750414/119846300-a3f05b00-bf27-11eb-8d12-2f7dfcf9c3b3.png)

**Comment by Shanmuganathanb** [comment]
Added it. Cheers ! Thanks buddy.

**Comment by vikasganiga05** [comment]
> Added it. Cheers ! Thanks buddy.

Your welcome :slightly_smiling_face:
