### ISSUE TITLE
Avoid using `text-align: justify`

### ISSUE THREAD

**Issue by vikasganiga05** [Shanmuganathanb/Portfolio_1#3]
Justifying text disrupts that even texture. Even if a page layout program is using subtle letter-spacing, or adjusting the width of the letters – these things, too, will make the texture uneven. So, my suggestion is to avoid using `text-align: justify` .

#### Screenshot

![image](https://user-images.githubusercontent.com/74750414/119850229-fc752780-bf2a-11eb-9af9-eb75783e047a.png)

**Comment by Shanmuganathanb** [comment]
Thanks for the suggestion. It is one of the precious one I got. I removed text-align actually.

**Comment by vikasganiga05** [comment]
> Thanks for the suggestion. It is one of the precious one I got. I removed text-align actually.

Awesome :tada:
